---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat
  namespace: tomcat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: 457017831224.dkr.ecr.ap-northeast-1.amazonaws.com/dev-tomcat
        name: tomcat
        ports:
          - containerPort: 808
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
      nodeSelector:
        app: tomcat